services:
  db-backend-nosql-standard-project:
    image: mongo:6.0.3
    container_name: db-backend-nosql-standard-project_${NODE_ENV}-${VERSION}
    expose:
      - 27017
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - db-backend-nosql-standard-project-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    networks:
      - default

  api-backend-nosql-standard-project:
    image: countergank/backend-nosql-standard-project:${NODE_ENV}-${VERSION}
    container_name: api-backend-nosql-standard-project_${NODE_ENV}-${VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - db-backend-nosql-standard-project
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
    networks:
      - default

volumes:
  db-backend-nosql-standard-project-data:
    driver: local

networks:
  default:
    name: backend-nosql-standard-project-net
    driver: bridge

  # microservice-name-net:
  #   name: microservice-name-net
  #   external: true
